version: '3'
services:
  app:
    image: test-docker
    environment:
          SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/base-db?createDatabaseIfNotExist=true
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: 123456
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - //var/run/docker.sock:/var/run/docker.sock
    build: ../
    depends_on:
      - db
    ports:
      - "8080:8080"
  #    network_mode: "host"
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: base-db
      #      MYSQL_USER: root
      #      MYSQL_PASSWORD: 12345678
      #      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3308:3306"
#    command: --default-authentication-plugin=mysql_native_password

#NEW VERSION
#version: '3'
#services:
#  db:
#    container_name: base-dbd
##    hostname: dongnam0106/base-db
#    image: mysql
#    restart: always
#    ports:
#      - "3308:3306"
#    volumes:
#      - base-db:/var/lib/mysql
#    environment:
#      MYSQL_DATABASE: base-db
#      MYSQL_USER: root
#      MYSQL_PASSWORD: 123456
#      MYSQL_ROOT_PASSWORD: 123456
#  #      MYSQL_ALLOW_EMPTY_PASSWORD: true
#  app:
#    container_name: base-be
##    hostname: dongnam0106/base-be
#    image: base-be
#    depends_on:
#      - db
#    build: ../
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/base-db?createDatabaseIfNotExist=true
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: 123456
#volumes:
#  base-db:
